//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kion
{
    using System;
    using System.Collections.Generic;
    
    public partial class dokuman
    {
        public int docId { get; set; }
        public string docTur { get; set; }
        public string docYol { get; set; }
        public long tckn { get; set; }
    }
}
