//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fakulte
    {
        public int fakId { get; set; }
        public string fakAd { get; set; }
        public int uniId { get; set; }
        public bool status { get; set; }
    }
}
