//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kionEntities1 : DbContext
    {
        public kionEntities1()
            : base("name=kionEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bolum> bolum { get; set; }
        public virtual DbSet<dokuman> dokuman { get; set; }
        public virtual DbSet<fakulte> fakulte { get; set; }
        public virtual DbSet<onKayit> onKayit { get; set; }
        public virtual DbSet<universite> universite { get; set; }
    }
}
