//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kion
{
    using System;
    using System.Collections.Generic;
    
    public partial class onKayit
    {
        public long tckn { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string anneAd { get; set; }
        public string anneSoyad { get; set; }
        public string babaAd { get; set; }
        public string babaSoyad { get; set; }
        public Nullable<int> uniId { get; set; }
        public Nullable<int> fakId { get; set; }
        public Nullable<int> bolId { get; set; }
        public Nullable<bool> ales { get; set; }
        public Nullable<bool> diploma { get; set; }
        public Nullable<bool> askerlik { get; set; }
        public Nullable<long> gsm { get; set; }
        public string email { get; set; }
    }
}
